modLoader="javafml"
loaderVersion="[41,)"
license="GPL3"

[[mods]]
modId="grenadesadozen"
version="1.0.99"
displayName="Grenades a Dozen (Dev. Branch)"
updateJSONURL=""
displayURL=""
logoFile="nzgexpansion_banner.png"
authors="zaeonNineZero, An0m3L1"
credits="MrCrayfish, An0m3L1, zaeonNineZero"
description='''
Addon for MrCrayfish's Gun Mod that adds multiple type of throwable grenades and explosives.
'''

[[dependencies.grenadesadozen]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.grenadesadozen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.grenadesadozen]]
    modId="framework"
    mandatory=true
    versionRange="[0.3.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.grenadesadozen]]
    modId="cgm"
    mandatory=true
    versionRange="[1.3.7,)"
    ordering="AFTER"
    side="BOTH"

[modproperties.grenadesadozen]
    catalogueImageIcon="nzgexpansion_icon.png"
